target = o_player;
move_speed = 0.5; // Adjust the speed as needed
state = "idle";
lunge_speed = 2; // Adjust the lunging speed as needed
lunge_cooldown = 0;
follow_distance = 100; 
lunge_cooldown_max = room_speed * 6; // 3 seconds between lunges (adjust as needed)
min_lunge_distance = 60;
stop_distance = 50
hp = 8